![imagen](./img/ejercicios.png)

## Ejercicio 1
1. Crea un array que vaya del 0 al 9 y que se llame `my_array`
2. Imprime por pantalla los elementos [9 7 5 3 1] en ese orden.

In [555]:
import numpy as np

In [556]:
my_array = np.arange(0,10)

print(my_array[9:0:-2])

[9 7 5 3 1]


## Ejercicio 2
Imprime por pantalla la secuencia [8 7] del array `my_array`

In [557]:
print(my_array[8:6:-1])

[8 7]


## Ejercicio 3
Imprime por pantalla la secuencia [2 1 0] de `my_array`

In [558]:
print(my_array[2::-1])

[2 1 0]


## Ejercicio 4
1. Crea una matriz de 4x5, con una secuencia del 1 al 20
2. Invierte totalmente la matriz. Tanto las filas, como las columnas

In [559]:
mi_matriz = np.arange(1,21).reshape(4,5)
print(mi_matriz)
# print(mi_matriz.T)
matriz_invertida = mi_matriz[::-1,::-1]
print(matriz_invertida)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
[[20 19 18 17 16]
 [15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


## Ejercicio 5

Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[1, 2],
       [6, 7]])
```

In [560]:
new_array = mi_matriz[:2,:2]
new_array

array([[1, 2],
       [6, 7]])

## Ejercicio 6
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 1,  3,  5],
       [11, 13, 15]])
```

In [561]:
mi_matriz[::2,::2]

array([[ 1,  3,  5],
       [11, 13, 15]])

## Ejercicio 7
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])
```

In [562]:
mi_matriz[:3,::-1]

array([[ 5,  4,  3,  2,  1],
       [10,  9,  8,  7,  6],
       [15, 14, 13, 12, 11]])

## Ejercicio 8
Dado el siguiente array:

```Python
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
```

Filtra el array para quedarte únicamente con los loros.

Resuélvelo de dos maneras diferentes

In [563]:
x = np.array(["Loro", "Perro", "Gato", "Loro", "Perro"])
x

array(['Loro', 'Perro', 'Gato', 'Loro', 'Perro'], dtype='<U5')

In [564]:
[i for i in x if i[0] == 'L']

[np.str_('Loro'), np.str_('Loro')]

In [565]:
filtro = x == 'Loro'
print(x[filtro])

['Loro' 'Loro']


## Ejercicio 9
Crea una secuencia de 20 elementos y transformala en un array compuesto por 2 matrices de 5x2

In [566]:
numeros = np.arange(1,21).reshape(2,5,2)
numeros

array([[[ 1,  2],
        [ 3,  4],
        [ 5,  6],
        [ 7,  8],
        [ 9, 10]],

       [[11, 12],
        [13, 14],
        [15, 16],
        [17, 18],
        [19, 20]]])

## Ejercicio 10
Obtén el siguiente array, partiendo de la matriz del ejercicio 4
```Python
array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])
```

In [567]:
mi_matriz[::-1,::-1]

array([[20, 19, 18, 17, 16],
       [15, 14, 13, 12, 11],
       [10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Ejercicio 11
Crea un array de 10 0s. ¿Cuánto ocupa en memoria?

Sustituye el 4to elemento por 1, e imprime el array por pantalla

In [568]:
array1 = np.zeros(10)
print(array1.nbytes)
array1[3] = 1
print(array1.nbytes)
array1

80
80


array([0., 0., 0., 1., 0., 0., 0., 0., 0., 0.])

## Ejercicio 12
Crea un vector que vaya del 10 al 49

Inviértelo

In [569]:
vector1 = np.arange(10,50)
vector1[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

## Ejericio 13
Encuentra los indices de los valores que no sean 0 del siguiente vector [1,2,0,0,4,0]. El output sería [0, 1, 4]. [Encuentra el método apropiado en la documentación.](https://numpy.org/doc/)

In [570]:
vector2 = np.array([1,2,0,0,4,0])
np.nonzero(vector2)[0]

array([0, 1, 4])

In [571]:
np.where(vector2 != 0)[0]

array([0, 1, 4])

## Ejercicio 14
Crea una matriz de numeros aleatorios 10x10. Encuentra los valores mínimo y máximo.

In [572]:
matriz = np.random.randint(1,1000,(10,10))
print(matriz)
print(matriz.min())
print(matriz.max())

[[779 616 265 716 369 201 168 678 656 295]
 [142 687  54 951 384 361 447 669  35 709]
 [709 136 367 274 275 214 604 478 279 686]
 [986 369  65 462 998 215 528 846 346 938]
 [310 239 303 603 684 924  50 659 384 165]
 [322 855 178 131 715 210 642  78 188 108]
 [480 466 153 459 198 328 538 411 112 212]
 [ 29 331 303 644 814 109 658 533 875 255]
 [953 593 479 303  24 895 773 870 605 153]
 [955 953  84 756 369 147 571 730 534  64]]
24
998


## Ejercicio 15
Crea un vector aleatorio de tamaño 30 y calcula su media

In [573]:
vector3 = np.random.randint(1,10,size=30)
vector3.mean()

np.float64(4.633333333333334)

## Ejercicio 16
Crea un array cuadrado de 2D, con las dimensiones que quiras, pero que todo el borde esté compuesto por 1s, y el interior por 0s

In [574]:
array2 = np.full((10,10),'1s')
array2[1:-1,1:-1] = '0s'
array2

array([['1s', '1s', '1s', '1s', '1s', '1s', '1s', '1s', '1s', '1s'],
       ['1s', '0s', '0s', '0s', '0s', '0s', '0s', '0s', '0s', '1s'],
       ['1s', '0s', '0s', '0s', '0s', '0s', '0s', '0s', '0s', '1s'],
       ['1s', '0s', '0s', '0s', '0s', '0s', '0s', '0s', '0s', '1s'],
       ['1s', '0s', '0s', '0s', '0s', '0s', '0s', '0s', '0s', '1s'],
       ['1s', '0s', '0s', '0s', '0s', '0s', '0s', '0s', '0s', '1s'],
       ['1s', '0s', '0s', '0s', '0s', '0s', '0s', '0s', '0s', '1s'],
       ['1s', '0s', '0s', '0s', '0s', '0s', '0s', '0s', '0s', '1s'],
       ['1s', '0s', '0s', '0s', '0s', '0s', '0s', '0s', '0s', '1s'],
       ['1s', '1s', '1s', '1s', '1s', '1s', '1s', '1s', '1s', '1s']],
      dtype='<U2')

## Ejercicio 17
Crea una mtriz de 8x8, y rellénala con 0s y 1s. Tienes que replicar:
```Python
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]
```

In [575]:
matriz_binomial = np.zeros((8,8), int)
matriz_binomial[::2,1::2] = 1
matriz_binomial[1::2,::2] = 1
matriz_binomial

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

## Ejercicio 18
Replica la matriz del apartado anterior, pero en este caso usando [la función `tile`](https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [576]:
a = np.array([0,1])
b = np.array([1,0])
matriz_inicial = np.matrix((a,b),int)
np.tile(matriz_inicial,(4,4))

matrix([[0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0],
        [0, 1, 0, 1, 0, 1, 0, 1],
        [1, 0, 1, 0, 1, 0, 1, 0]])

## Ejercicio 19
Crea una matriz aleatoria de 5x5 y normaliza sus valores. Para normalizar tienes que restar sus valores por la media(`np.mean`) y dividir el resultado por la desviación estándar(`np.std`).

In [577]:
matriz_a = np.random.randint(1,100,(5,5))

media = matriz_a.mean()
desviacion_std = matriz_a.std()
print(f'media: {media}, desviacion: {desviacion_std}\n')

matriz_a_normalizada = (matriz_a-media)/desviacion_std

print(f'{matriz_a}\n')
print(matriz_a_normalizada)

media: 46.88, desviacion: 28.47640426739303

[[24 34 46  5 61]
 [78 46 33 31 94]
 [14 83 77 69 92]
 [15 77 45 42 18]
 [ 6 26 91 54 11]]

[[-0.80347223 -0.4523043  -0.03090278 -1.4706913   0.49584912]
 [ 1.0928346  -0.03090278 -0.48742109 -0.55765468  1.6547033 ]
 [-1.15464016  1.26841857  1.05771781  0.77678347  1.58446971]
 [-1.11952337  1.05771781 -0.06601957 -0.17136995 -1.01417299]
 [-1.43557451 -0.73323864  1.54935292  0.25003157 -1.25999054]]


## Ejercicio 20
1. Crea una secuencia de números que vayan del 0 al 10.
2. Crea un nuevo array, que parta del anterior, pero sustituya por el valor -1, todos los elementos cuyo valor se encuentre entre el 3 y el 8.
3. Crea un nuevo array que niegue todos los elementos entre el 3 y el 8

In [578]:
array5 = np.arange(11)
array5_modificado = array5.copy()
array5_modificado[3:9] = -1
array5_negado = array5_modificado.copy()
array5_negado = ~(array5_modificado == -1)
print(array5)
print(array5_modificado)
print(array5_negado)


[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  1  2 -1 -1 -1 -1 -1 -1  9 10]
[ True  True  True False False False False False False  True  True]


## Ejercicio 21
#### Bonus track. Mini hundir la flota
1. Crea un tablero de 10x10 relleno del carácter espacio ( ).
2. Posiciona un par de barcos en [(0,1), (1,1)] y [(1,3), (1,4), (1,5), (1,6)]. Los barcos serán Os mayúsculas. Como ves, un barco de dos posiciones de eslora y otro de cuatro.
3. Recibe un disparo en uno de los barcos, sustituyendo la O por una X
4. Recibe un disparo en agua, sustituyendo uno de los espacios por un guión: -
5. Ignorando los disparos recibidos, ahora prueba a posicionar otro barco de 4 posiciones dentro del tablero, pero **de manera ALEATORIA.**

**TIP apartado 5**: El barco tendrá una posición inicial aleatoria dentro del tablero, y una orientación también aleatoria (N,S,E,O).

Por ejemplo, si tu posicion inicial fuese (5,0) y la orientación O, no podrias ponerlo porque se sale del tablero. Ahora bien, si fuese orientación este, si podrías, y ocuparía las posiciones [(5,0), (5,1), (5,2), (5,3)]. Por tanto tendrás que iterar con un bucle si es posible encajar el barco en el tablero, y el bucle terminará cuando lo consigas encajar. **Ojo con las posiciones donde ya hay barco!!!**

Usa `import random` para elegir las coordenadas aleatorias.

In [579]:
tablero = np.full((10,10),' ')
tablero

array([[' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')

In [580]:
tablero[0:2,1] = 'O'
tablero[1,3:7] = 'O'
tablero

array([[' ', 'O', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', 'O', ' ', 'O', 'O', 'O', 'O', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')

In [581]:
tablero[1,6] = 'X'
tablero

array([[' ', 'O', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', 'O', ' ', 'O', 'O', 'O', 'X', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')

In [582]:
tablero[0,0] = '-'
tablero

array([['-', 'O', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', 'O', ' ', 'O', 'O', 'O', 'X', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')

In [ ]:
barco1 = np.full(4,'O')

In [584]:
tablero

array([['-', 'O', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', 'O', ' ', 'O', 'O', 'O', 'X', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')

In [592]:
import random

def posicionar_barco(barco):
    tamano = len(barco)

    while True:
        fila = random.randint(0, 9)
        columna = random.randint(0, 9)
        orientacion = random.choice(['H', 'V'])

        if orientacion == 'H':
            if columna + tamano <= 10 and all(tablero[fila, columna + i] == ' ' for i in range(tamano)):
                tablero[fila, columna:columna + tamano] = barco
                break

        elif orientacion == 'V':
            if fila + tamano <= 10 and all(tablero[fila + i, columna] == ' ' for i in range(tamano)):
                tablero[fila:fila + tamano, columna] = barco
                break

In [593]:
posicionar_barco(barco1)

In [594]:
tablero

array([['-', 'O', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', 'O', ' ', 'O', 'O', 'O', 'X', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', 'O', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', 'O', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', 'O', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', 'O', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' '],
       [' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ']], dtype='<U1')